[tool.poetry]
name = "harrygobert"
version = "0.1.0"
description = "Using embeddings to find Environmental Footprint score of food products."
authors = ["Bas Krahmer"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"


[tool.poetry.group.test.dependencies]
pytest = "^7.1.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
