AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Timeout: 300
    MemorySize: 3008

Parameters:
  Env:
    Type: String
    Default: dev
    AllowedValues:
      - prod
      - dev
    Description: Enter Env name prod or dev.

Resources:

  CFDistribution:
    Type: "AWS::CloudFront::Distribution"
    Properties:
      DistributionConfig:
        Enabled: true
        HttpVersion: http2
        # List of origins that Cloudfront will connect to
        Origins:
          - Id: s3-website
            DomainName:  !Select [2, !Split ["/", !GetAtt S3Bucket.WebsiteURL]]
            CustomOriginConfig:
              HTTPPort: '80'
              HTTPSPort: '443'
              OriginProtocolPolicy: http-only
        DefaultCacheBehavior:
          # Compress resources automatically ( gzip )
          Compress: 'true'
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
          ForwardedValues:
            QueryString: true
          TargetOriginId: s3-website
          ViewerProtocolPolicy: redirect-to-https
        Aliases:
          - harrygobert.org
        ViewerCertificate:
          SslSupportMethod: sni-only
#          MinimumProtocolVersion: TLSv1.2_2021
          AcmCertificateArn: arn:aws:acm:us-east-1:977248756071:certificate/18f9407f-fd9d-47e0-b9c5-ffaa78b22905

  DNSAliasRecord:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneId: Z05811542R6T772RGSDBU
      RecordSets:
        - Name: www.harrygobert.org
          Type: A
          AliasTarget:
            HostedZoneId: Z2FDTNDATAQYW2
            DNSName: !GetAtt
              - CFDistribution
              - DomainName

  CloudFrontOriginAccessIdentity:
    Type: 'AWS::CloudFront::CloudFrontOriginAccessIdentity'
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: 'Serverless website OA'

  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: PublicRead
      BucketName: www.harrygobert.org
      WebsiteConfiguration:
        RedirectAllRequestsTo:
          HostName: harrygobert.org
          Protocol: https

  S3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref S3Bucket
      PolicyDocument:
        # Restricting access to cloudfront only.
        Statement:
          - Effect: Allow
            Action: 's3:GetObject'
            Resource:
              - !Sub "arn:aws:s3:::${S3Bucket}/*"
            Principal:
              AWS: !Sub "arn:aws:iam::cloudfront:user/CloudFront Origin Access Identity ${CloudFrontOriginAccessIdentity}"

  ApiCertificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Sub api-${Env}.harrygobert.org
      ValidationMethod: DNS

  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref Env
      # SAM will automatically add AllowMethods with a list of methods for this API
      Cors: "'www.harrygobert.org'"
      EndpointConfiguration: REGIONAL
      Domain:
        DomainName: !Sub api-${Env}.harrygobert.org
        CertificateArn: !Ref ApiCertificate
        Route53:
          HostedZoneName: "harrygobert.org."

  InferenceFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      PackageType: Image
      Events:
        Inference:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /classify
            Method: any
            RestApiId:
              Ref: ApiGatewayApi
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: .
      DockerTag: python3.9-v1

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  InferenceApi:
    Description: "API Gateway endpoint URL for Prod Env for Inference function"
    Value: !Sub "https://${ApiGatewayApi}.execute-api.${AWS::Region}.amazonaws.com/{Env}/classify/"
