name: Deploy Infrastructure

on: [ push, pull_request ]

jobs:
  deploy-dev:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:

      - name: Checkout
        uses: actions/checkout@v3

      #      - name: Update Docker image
      #        uses: ./.github/actions/push-docker
      #        with:
      #          env: dev
      #          role_arn: ${{ secrets.DEV_DEPLOY_ROLE }}
      #          ecr_repository: 81181825

      - name: Deploy to dev
        uses: ./.github/actions/deploy
        with:
          env: dev
          role_arn: ${{ secrets.DEV_DEPLOY_ROLE }}
          state_bucket: tfstate-harrygobert-dev
          cloudflare_api_token: ${{ secrets.CLOUDFLARE_API_TOKEN }}

      - name: Deploy frontend to dev
        uses: ./.github/actions/build-frontend
        with:
          env: dev
          role_arn: ${{ secrets.DEV_DEPLOY_ROLE }}
          bucket_name: harrygobert-dev

  deploy-prod:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    if: ${{ github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main'}}

    steps:

      - name: Checkout
        uses: actions/checkout@v3

      #      - name: Update Docker image
      #        uses: ./.github/actions/push-docker
      #        with:
      #          env: prod
      #          role_arn: ${{ secrets.PROD_DEPLOY_ROLE }}
      #          ecr_repository: foodpred

      - name: Deploy to prod
        uses: ./.github/actions/deploy
        with:
          env: prod
          role_arn: ${{ secrets.PROD_DEPLOY_ROLE }}
          state_bucket: tfstate-harrygobert-prod
          cloudflare_api_token: ${{ secrets.CLOUDFLARE_API_TOKEN }}

      - name: Deploy frontend to prod
        uses: ./.github/actions/build-frontend
        with:
          env: prod
          role_arn: ${{ secrets.PROD_DEPLOY_ROLE }}
          bucket_name: harrygobert-prod
